version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysqlDatabase:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

networks:
  app-network: